services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://localhost:1337
      - STRAPI_API_URL=http://backend:1337
      - NODE_ENV=development
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    build:
      context: ./backend/forever-faded
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - JWT_SECRET=your-secret-key
      - ADMIN_JWT_SECRET=your-admin-secret
      - APP_KEYS=key1,key2,key3,key4
    volumes:
      - ./backend/forever-faded:/app
      - /app/node_modules
      - ./backend/forever-faded/.tmp/data.db:/app/.tmp/data.db
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:1337/api/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  backend_data: