

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  backend:
    platform: linux/amd64
    build:
      context: ./backend/forever-faded
      dockerfile: Dockerfile
    ports:
      - "1337:5000"
    volumes:
      - ./backend/forever-faded:/app
      - /app/node_modules

networks:
  default:
    driver: bridge